#ifndef D__PIO_ARM_WS_MCAL_MSYSTICK_DRIVER_INC_MCAL_MSYSTICK_MSYSTICK_CONFIG_H_
#define D__PIO_ARM_WS_MCAL_MSYSTICK_DRIVER_INC_MCAL_MSYSTICK_MSYSTICK_CONFIG_H_

/*
 * OPTIONS :
 *           SYSTICK_INTERRUPT_OFF   
 *           SYSTICK_INTERRUPT_ON   
 */
#define SYSTICK_INTERRUPT   SYSTICK_INTERRUPT_ON

/*
 * OPTIONS :
 *           SYSTICK_CLK_SRC_AHB_DIV_BY_8
 *           SYSTICK_CLK_SRC_AHB
 */
#define SYSTICK_CLK_SRC  SYSTICK_CLK_SRC_AHB

//define Clock Source of the System 
#define CLK_SRC 16000000

#endif 